### ISSUE TITLE
Unable to build [PYTHON_LIBRARIES-NOTFOUND]

### ISSUE THREAD

**Issue by RedNicStone** [otherlab/geode#104]
I am unable to build geode due to missing python library (which are installed).

Here is what cmake returns for me:
```cmake
-- Could NOT find JPEG (missing: JPEG_LIBRARY JPEG_INCLUDE_DIR) 
-- GMP found in /usr/lib64/libgmp.so
-- Python binary found at /usr/bin/python
-- Numpy found in /usr/lib64/python3.9/site-packages/numpy/core/include
-- Looking for python pkgconfig in /usr/lib64/pkgconfig
-- pkg-config did not set Python library dirs. Falling back to sysconfig
-- Expecting to find  in /usr/lib64
-- find_library returned _PYTHON_LIBRARIES-NOTFOUND
CMake Warning at FindPathPython.cmake:78 (message):
   Unable to find full path to python lib
Call Stack (most recent call first):
  CMakeLists.txt:40 (find_package)


ERROR Unable to find python library
-- Python bindings for geode disabled
-- Building array module.
-- Building python module.
-- Building force module.
-- Building utility module.
-- Building math module.
-- Building geometry module.
-- Building random module.
-- Building structure module.
-- Building solver module.
-- Building image module.
-- Building svg_to_bezier module.
-- Building mesh module.
-- Building value module.
-- Building vector module.
-- Building exact module.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/***/geode
```
Since python can not be found, the variable `GEODE_PYTHON` is set to `NO` preventing the python module from being built.
This again causes most dependencies to break, for example decimate.cpp, line 410:

```cpp
/home/***/geode/geode/mesh/decimate.cpp:410:24: error: ‘PyFieldId’ does not name a type; did you mean ‘FieldId’?
  410 |                  const PyFieldId& X_id,
      |                        ^~~~~~~~~
      |                        FieldId
```
As it is not defined:

[ids.cpp]
```cpp
#ifdef GEODE_PYTHON

[...]

GEODE_DEFINE_TYPE(PyFieldId);

template<> GEODE_DEFINE_TYPE(PyRange<IdIter<VertexId>>);
template<> GEODE_DEFINE_TYPE(PyRange<IdIter<FaceId>>);
template<> GEODE_DEFINE_TYPE(PyRange<IdIter<HalfedgeId>>);
#endif
```

To prevent all this I tried to replace the `FindPathPython.cmake` search function by the built in CMake Python search function:
```cmake
#find_package(PathPython)
find_package(Python2 COMPONENTS Interpreter Development NumPy)
```
Which worked but caused other errors to occur:
```cpp
/home/***/geode/geode/exact/../../geode/python/to_python.h: In function ‘geode::PyObject* geode::to_python(int)’:
/home/***/geode/geode/exact/../../geode/python/to_python.h:41:10: error: ‘PyInt_FromLong’ was not declared in this scope; did you mean ‘PyLong_FromLong’?
   41 |   return PyInt_FromLong(value);
      |          ^~~~~~~~~~~~~~
      |          PyLong_FromLong
/home/***/geode/geode/exact/../../geode/python/to_python.h: In function ‘geode::PyObject* geode::to_python(unsigned int)’:
/home/***/geode/geode/exact/../../geode/python/to_python.h:45:10: error: ‘PyInt_FromSize_t’ was not declared in this scope; did you mean ‘PyLong_FromSize_t’?
   45 |   return PyInt_FromSize_t(value);
      |          ^~~~~~~~~~~~~~~~
      |          PyLong_FromSize_t
/home/***/geode/geode/exact/../../geode/python/to_python.h: In function ‘geode::PyObject* geode::to_python(long int)’:
/home/***/geode/geode/exact/../../geode/python/to_python.h:49:10: error: ‘PyInt_FromLong’ was not declared in this scope; did you mean ‘PyLong_FromLong’?
   49 |   return PyInt_FromLong(value);
      |          ^~~~~~~~~~~~~~
      |          PyLong_FromLong
/home/***/geode/geode/exact/../../geode/python/to_python.h: In function ‘geode::PyObject* geode::to_python(const char*)’:
/home/***/geode/geode/exact/../../geode/python/to_python.h:77:10: error: ‘PyString_FromString’ was not declared in this scope; did you mean ‘PyLong_FromString’?
   77 |   return PyString_FromString(value);
      |          ^~~~~~~~~~~~~~~~~~~
      |          PyLong_FromString
/home/***/geode/geode/exact/../../geode/python/to_python.h: In function ‘geode::PyObject* geode::to_python(const string&)’:
/home/***/geode/geode/exact/../../geode/python/to_python.h:81:10: error: ‘PyString_FromStringAndSize’ was not declared in this scope; did you mean ‘PyBytes_FromStringAndSize’?
   81 |   return PyString_FromStringAndSize(value.c_str(),(Py_ssize_t)value.size());
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |          PyBytes_FromStringAndSize
In file included from /home/***/geode/geode/exact/../../geode/vector/Vector.h:18,
                 from /home/***/geode/geode/exact/../../geode/array/RawArray.h:13,
                 from /home/***/geode/geode/exact/../../geode/array/Array.h:21,
                 from /home/***/geode/geode/exact/../../geode/array/convert.h:8,
                 from /home/***/geode/exact/circle_csg.cpp:3:
/home/***/geode/geode/exact/../../geode/python/to_python.h: In function ‘geode::PyObject* geode::to_python(char)’:
/home/***/geode/geode/exact/../../geode/python/to_python.h:93:10: error: ‘PyString_FromString’ was not declared in this scope; did you mean ‘PyLong_FromString’?
   93 |   return PyString_FromString(s);
      |          ^~~~~~~~~~~~~~~~~~~
      |          PyLong_FromString
In file included from /usr/include/python3.9/objimpl.h:208,
                 from /usr/include/python3.9/Python.h:89,
                 from /home/***/geode/geode/exact/../../geode/python/config.h:53,
                 from /home/***/geode/geode/exact/../../geode/config.h:8,
                 from /home/***/geode/geode/exact/../../geode/utility/config.h:6,
                 from /home/***/geode/geode/exact/../../geode/utility/type_traits.h:4,
                 from /home/***/geode/geode/exact/../../geode/array/forward.h:6,
                 from /home/***/geode/geode/exact/../../geode/array/ArrayBase.h:6,
                 from /home/***/geode/geode/exact/../../geode/array/Array.h:20,
                 from /home/***/geode/geode/exact/../../geode/array/convert.h:8,
                 from /home/***/geode/geode/exact/circle_csg.cpp:3:
/home/***/geode/geode/exact/../../geode/python/Buffer.h: In static member function ‘static geode::Buffer* geode::Buffer::new_(int)’:
/usr/include/python3.9/cpython/objimpl.h:77:19: error: cannot convert ‘PyObject*’ {aka ‘_object*’} to ‘geode::Buffer*’ in return
   77 |     _PyObject_INIT(_PyObject_CAST(op), (typeobj))
      |     ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                   |
      |                   PyObject* {aka _object*}
/home/***/geode/geode/exact/../../geode/python/config.h:143:30: note: in expansion of macro ‘PyObject_INIT’
  143 | #define GEODE_PY_OBJECT_INIT PyObject_INIT
      |                              ^~~~~~~~~~~~~
/home/***/geode/geode/exact/../../geode/python/Buffer.h:45:12: note: in expansion of macro ‘GEODE_PY_OBJECT_INIT’
   45 |     return GEODE_PY_OBJECT_INIT(self,&pytype);
      |            ^~~~~~~~~~~~~~~~~~~~
In file included from /home/***/geode/geode/exact/../../geode/array/convert.h:14,
                 from /home/***/geode/geode/exact/circle_csg.cpp:3:
/home/***/geode/geode/exact/../../geode/python/numpy.h: In function ‘typename geode::enable_if<geode::{anonymous}::NumpyIsStatic<TV>, TV>::type geode::{anonymous}::from_numpy(geode::PyObject*)’:
/home/***/geode/geode/exact/../../geode/python/numpy.h:251:6: error: there are no arguments to ‘PyInt_Check’ that depend on a template parameter, so a declaration of ‘PyInt_Check’ must be available [-fpermissive]
  251 |   if(PyInt_Check(object) && !PyInt_AS_LONG(object))
      |      ^~~~~~~~~~~
/home/***/geode/geode/exact/../../geode/python/numpy.h:251:6: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
/home/***/geode/geode/exact/../../geode/python/numpy.h:251:30: error: there are no arguments to ‘PyInt_AS_LONG’ that depend on a template parameter, so a declaration of ‘PyInt_AS_LONG’ must be available [-fpermissive]
  251 |   if(PyInt_Check(object) && !PyInt_AS_LONG(object))
      |                              ^~~~~~~~~~~~~
```
I am not very familiar with building python, but my wild guess would be that the wrong version of python was loaded (3.9 instead of 2.x).
See `In file included from /usr/include/python3.9`.
Just to see what happens I ran the build in a python 2.7 vitualenv, with no effect (Which dose not surprise me given that CMake operates globally, eg virtualenv dose not change the python lib paths).

It would greatly appreciate your help to get this gorgeous library up and running!

_Some paths have been replaced with ***_

**Comment by mcbride** [comment]
fixed by fad251c. python wrappers were being built even if python was disabled
